routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductTypeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [OrderController::class, 'landing']);

Route::middleware(['auth:sanctum', 'verified'])->resource('product-types', ProductTypeController::class);
Route::middleware(['auth:sanctum', 'verified'])->resource('products', ProductController::class);
Route::middleware(['auth:sanctum', 'verified'])->resource('orders', OrderController::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'description', 'type_id', 'image'];

}

app/Models/ProductType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductType extends Model
{
    use HasFactory;
    protected $fillable = ['name'];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        //print_r($request);
        $type = $request->input('type');

        if(!empty($type)){
            $products = DB::table('products')
                ->where('type_id', '=', $type)
                ->get();
            return view('product.list', ['products' => $products]);
        } else {
            return view('product.list', ['products' => Product::all()]);
        }
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('product.create', []);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $product = new Product();

        $str = Str::random(10);
        $extension = $request->image->extension();
        $file_name = $str . "." . $extension;
        $request->image->storeAs('/public/images', $file_name);

        $product->name =  $request->input('name');
        $product->description =  $request->input('description');
        $product->type_id =  $request->input('type_id');
        $product->image =  $file_name;
        $product->save();
        return redirect()->route('products.index')
            ->with('success', 'Product updated successfully');

        #$request->image->storeAs('images', 'filename.jpg');
        #$product->save($request->all());
        #if ($request->hasFile('image')) {
        #    //  Let's do everything here
        #    if ($request->file('image')->isValid()) {
        #        //
        #        $validated = $request->validate([
        #            'name' => 'string|max:40',
        #            'image' => 'mimes:jpeg,png|max:1014',
        #        ]);
        #        $extension = $request->image->extension();
        #        $request->image->storeAs('/public', $validated['name'].".".$extension);
        #        $url = Storage::url($validated['name'].".".$extension);
        #        $file = File::create([
        #           'name' => $validated['name'],
        #            'url' => $url,
        #        ]);
        #        Session::flash('success', "Success!");
        #        return \Redirect::back();
        #    }
        #}
        #abort(500, 'Could not upload image :(');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        //
        return view('product.edit', ['product' => Product::find($product->id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
        $request->validate([
            'name' => 'required'
        ]);

        if ($request->hasFile('image')) {
            if ($request->file('image')->isValid()) {
                $existing_file = $product->image;
                $path_existing_file =  "/public/images/" . $existing_file;
                Storage::delete($path_existing_file);

                $str = Str::random(10);
                $extension = $request->image->extension();
                $file_name = $str . "." . $extension;
                $request->image->storeAs('/public/images', $file_name);
                
                $product->name =  $request->input('name');
                $product->description =  $request->input('description');
                $product->type_id =  $request->input('type_id');
                $product->image =  $file_name;
                $product->save();
            }
        } else {
            $product->update($request->all());
        }

        return redirect()->route('products.index')
            ->with('success', 'Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
        $existing_file = $product->image;
        $path_existing_file =  "/public/images/" . $existing_file;
        
        Storage::delete($path_existing_file);
        $product->delete();

        return redirect()->route('products.index')
            ->with('success', 'Se ha eliminado correctamente');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/product/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Crear') }}
        </h2>
    </x-slot>


    <div class="py-12">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                {{-- INIT CONTENT --}}
                <div class="flex justify-center py-2 px-2">

                    <div class="w-3/4 rounded px-6 mt-3">
                        {{-- FORM --}}
                        <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('POST')

                            <div class="md:flex md:items-center mb-6">
                                <div class="md:w-1/3">
                                    <x-jet-label for="name" value="{{ __('Nombre') }}"
                                        class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" />
                                </div>
                                <div class="md:w-2/3">
                                    <input id="name"
                                        class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                                        type="text" name="name" required />
                                </div>
                            </div>


                            <div class="md:flex md:items-center mb-6">
                                <div class="md:w-1/3">
                                    <x-jet-label for="desc" value="{{ __('Descripción') }}"
                                        class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" />
                                </div>
                                <div class="md:w-2/3">
                                    <textarea name="description" id="description" cols="30" rows="3" required class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500">
                                        
                                    </textarea>
                                </div>
                            </div>

                            <div class="md:flex md:items-center mb-6">
                                <div class="md:w-1/3">
                                    <x-jet-label for="name" value="{{ __('Tipo') }}"
                                        class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" />
                                </div>
                                <div class="md:w-2/3">
                                    <select name="type_id" id="type_id" required class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500">
                                        <option value="1">Gorra</option>
                                        <option value="2">Mascarilla</option>
                                    </select>
                                </div>
                            </div>

                            <div class="md:flex md:items-center mb-6">
                                <div class="md:w-1/3">
                                    <x-jet-label for="name" value="{{ __('Imagen') }}"
                                        class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" />
                                </div>
                                <div class="md:w-2/3">
                                    <input id="name"
                                        class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                                        type="file" name="image" required />
                                </div>
                            </div>




                            <div class="flex items-center justify-end mt-4">

                                <x-jet-button class="ml-4 bg-indigo-500">
                                    {{ __('Guardar') }}
                                </x-jet-button>
                            </div>

                        </form>
                        {{-- END FORM --}}
                    </div>
                    {{-- END CONTENT --}}
                </div>
            </div>
        </div>

</x-app-layout>

resources/views/product/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Editar') }} - {{ $product->name }}
        </h2>
    </x-slot>


    <div class="py-12">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                {{-- INIT CONTENT --}}
                <div class="flex justify-center py-2 px-2">

                    <div class="w-3/4 rounded px-6 mt-3">
                        {{-- FORM --}}
                        <form action="{{ route('products.update', $product->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')

                            <div class="md:flex md:items-center mb-6">
                                <div class="md:w-1/3">
                                    <x-jet-label for="name" value="{{ __('Nombre') }}"
                                        class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" />
                                </div>
                                <div class="md:w-2/3">
                                    <input id="name"
                                        class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                                        type="text" name="name" value="{{ $product->name }}" required />
                                </div>
                            </div>


                            <div class="md:flex md:items-center mb-6">
                                <div class="md:w-1/3">
                                    <x-jet-label for="desc" value="{{ __('Descripción') }}"
                                        class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" />
                                </div>
                                <div class="md:w-2/3">
                                    <textarea name="description" id="description" cols="30" rows="3" required class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500">
                                        {{ $product->description }}
                                    </textarea>
                                </div>
                            </div>

                            <div class="md:flex md:items-center mb-6">
                                <div class="md:w-1/3">
                                    <x-jet-label for="name" value="{{ __('Tipo') }}"
                                        class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" />
                                </div>
                                <div class="md:w-2/3">
                                    <select name="type_id" id="type_id" value="{{ $product->type_id }}" required class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500">
                                        <option value="1">Gorra</option>
                                        <option value="2">Mascarilla</option>
                                    </select>
                                </div>
                            </div>

                            <div class="md:flex md:items-center mb-6">
                                <div class="md:w-1/3">
                                    <x-jet-label for="name" value="{{ __('Imagen') }}"
                                        class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" />
                                </div>
                                <div class="md:w-2/3">
                                    <input id="name"
                                        class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                                        type="file" name="image" />
                                </div>
                            </div>




                            <div class="flex items-center justify-end mt-4">

                                <x-jet-button class="ml-4 bg-indigo-500">
                                    {{ __('Guardar') }}
                                </x-jet-button>
                            </div>

                        </form>
                        {{-- END FORM --}}
                    </div>
                    {{-- END CONTENT --}}
                </div>
            </div>
        </div>

</x-app-layout>

resources/views/product/list.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Productos') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                {{-- INIT CONTENT --}}
                <div class="flex justify-center py-2 px-2">

                    <div class="bg-gray-100 w-3/4 rounded px-6">
                        <div class="border-l-4 border-indigo-400 -ml-6 pl-6 flex items-center justify-between my-4">
                            <div class="font-semibold text-gray-800">
                                Catalogo de productos
                            </div>
                            <div>
                                <form id="deleteForm" action="{{ route('products.index') }}" method="GET">
                                    {{-- @csrf --}}
                                    @method('GET')
                                    <select name="type" class="bg-gray-200 appearance-none border-2 border-gray-200 rounded py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500">
                                        <option value="1">Gorra</option>
                                        <option value="2">Mascarilla</option>
                                    </select>
                                    <button type="submit" title="delete" style="border: none; background-color:transparent;">
                                        <i class="fa fa-search fa-lg text-indigo-400 mr-4"></i>
                                    </button>
                                </form>
                            </div>
                            <div class="text-indigo-400">

                                <x-jet-nav-link href="{{ route('products.create') }}"
                                    :active="request()->routeIs('products')">
                                    <i class="fa fa-plus fa-lg text-indigo-400 mr-4"></i>
                                </x-jet-nav-link>
                            </div>
                        </div>
                        <hr class="-mx-6" />
                        @foreach ($products as $product)
                            <div class="flex items-center justify-between my-4">
                                <div class="w-30">
                                    <img class="w-20 h-20" src="{{ URL::to('/') }}/storage/images/{{$product->image}}">
                                </div>
                                <div class="flex-1 pl-2">
                                    <div class="text-gray-700 font-semibold">
                                        {{ $product->name }}
                                    </div>
                                    <div class="text-gray-600 font-thin py-2 px-2">
                                        {{ $product->description }}
                                    </div>
                                </div>

                                <div>

                                    <form id="deleteForm" action="{{ route('products.destroy', $product->id) }}" method="POST">
                                        <x-jet-nav-link href="{{ route('products.edit', $product->id) }}"
                                            :active="request()->routeIs('products')">
                                            <i class="fa fa-edit fa-lg text-indigo-400 mr-4"></i>
                                        </x-jet-nav-link>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" title="delete"
                                            style="border: none; background-color:transparent;"
                                            onclick="return confirm('¿Esta seguro que desea eliminar?')">
                                            <i class="text-indigo-400 fas fa-trash fa-lg text-danger"></i>

                                        </button>
                                    </form>
                                </div>

                                <div class="text-indigo-400">

                                </div>
                            </div>
                            <hr class="boder-b-0 my-4" />
                        @endforeach
                    </div>
                </div>
                {{-- END CONTENT --}}
            </div>
        </div>
    </div>
</x-app-layout>
php artisan db:seed --class=ProductsTableSeeder