routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductTypeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [OrderController::class, 'landing']);

Route::middleware(['auth:sanctum', 'verified'])->resource('product-types', ProductTypeController::class);
Route::middleware(['auth:sanctum', 'verified'])->resource('products', ProductController::class);
Route::middleware(['auth:sanctum', 'verified'])->resource('orders', OrderController::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Controllers/ProductTypeController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProductType;
use Illuminate\Http\Request;

class ProductTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('product_type.list', ['product_types' => ProductType::all()]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('product_type.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $productType = new ProductType();
        $productType->name =  $request->input('name');
        $productType->save();

        return redirect()->route('product-types.index')
            ->with('success', 'Actualizado correctametne');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ProductType  $productType
     * @return \Illuminate\Http\Response
     */
    public function show(ProductType $productType)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ProductType  $productType
     * @return \Illuminate\Http\Response
     */
    public function edit(ProductType $productType)
    {
        //
        return view('product_type.edit', ['product_type' => ProductType::find($productType->id)]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ProductType  $productType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ProductType $productType)
    {
        //
        $request->validate([
            'name' => 'required'
        ]);
        $productType->update($request->all());

        return redirect()->route('product-types.index')
            ->with('success', 'Actualizado correctametne');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ProductType  $productType
     * @return \Illuminate\Http\Response
     */
    public function destroy(ProductType $productType)
    {
        //
        $productType->delete();

        return redirect()->route('product-types.index')
            ->with('success', 'Se ha eliminado correctamente');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/product_type/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Crear') }}
        </h2>
    </x-slot>


    <div class="py-12">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                {{-- INIT CONTENT --}}
                <div class="flex justify-center py-2 px-2">

                    <div class="w-3/4 rounded px-6 mt-3">
                        {{-- FORM --}}
                        <form action="{{ route('product-types.store') }}" method="POST">
                            @csrf
                            @method('POST')

                            <div class="md:flex md:items-center mb-6">
                                <div class="md:w-1/3">
                                    <x-jet-label for="name" value="{{ __('Nombre') }}"
                                        class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" />
                                </div>
                                <div class="md:w-2/3">
                                    <input id="name"
                                        class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                                        type="text" name="name" required />
                                </div>
                            </div>






                            <div class="flex items-center justify-end mt-4">

                                <x-jet-button class="ml-4 bg-indigo-500">
                                    {{ __('Guardar') }}
                                </x-jet-button>
                            </div>

                        </form>
                        {{-- END FORM --}}
                    </div>
                    {{-- END CONTENT --}}
                </div>
            </div>
        </div>

</x-app-layout>

resources/views/product_type/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Editar') }} - {{ $product_type->name }}
        </h2>
    </x-slot>


    <div class="py-12">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                {{-- INIT CONTENT --}}
                <div class="flex justify-center py-2 px-2">

                    <div class="w-3/4 rounded px-6 mt-3">
                        {{-- FORM --}}
                        <form action="{{ route('product-types.update', $product_type->id) }}" method="POST">
                            @csrf
                            @method('PUT')

                            <div class="md:flex md:items-center mb-6">
                                <div class="md:w-1/3">
                                    <x-jet-label for="name" value="{{ __('Nombre') }}"
                                        class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" />
                                </div>
                                <div class="md:w-2/3">
                                    <input id="name"
                                        class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                                        type="text" name="name" value="{{ $product_type->name }}" required />
                                </div>
                            </div>






                            <div class="flex items-center justify-end mt-4">

                                <x-jet-button class="ml-4 bg-indigo-500">
                                    {{ __('Guardar') }}
                                </x-jet-button>
                            </div>

                        </form>
                        {{-- END FORM --}}
                    </div>
                    {{-- END CONTENT --}}
                </div>
            </div>
        </div>

</x-app-layout>

resources/views/product_type/list.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Tipo de productos') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                {{-- INIT CONTENT --}}
                <div class="flex justify-center py-2 px-2">
                    
                    <div class="bg-gray-100 w-3/4 rounded px-6">
                        <div class="border-l-4 border-indigo-400 -ml-6 pl-6 flex items-center justify-between my-4">
                            <div class="font-semibold text-gray-800">
                                Catalogo de Tipos de productos
                            </div>
                            <x-jet-nav-link href="{{ route('product-types.create') }}"
                                :active="request()->routeIs('product-types')">
                                <i class="fa fa-plus fa-lg text-indigo-400 mr-4"></i>
                            </x-jet-nav-link>
                        </div>
                        <hr class="-mx-6" />
                        @foreach ($product_types as $product_type)
                            <div class="flex items-center justify-between my-4">
                                {{-- <div class="w-16">
                                    <img class="w-12 h-12 rounded-full" src="https://source.unsplash.com/50x50/?nature">
                                </div> --}}
                                <div class="flex-1 pl-2">
                                    <div class="text-gray-700 font-semibold">
                                        {{ $product_type->name }}
                                    </div>
                                </div>

                                
                                <div class="text-red-400">
                                    <form id="deleteForm" action="{{ route('product-types.destroy', $product_type->id) }}" method="POST">
                                        <x-jet-nav-link href="{{ route('product-types.edit', $product_type->id) }}"
                                            :active="request()->routeIs('product-types')">
                                            <i class="fa fa-edit fa-lg text-indigo-400 mr-4"></i>
                                        </x-jet-nav-link>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" title="delete"
                                            style="border: none; background-color:transparent;"
                                            onclick="return confirm('¿Esta seguro que desea eliminar?')">
                                            <i class="text-indigo-400 fas fa-trash fa-lg text-danger"></i>

                                        </button>
                                    </form>
                                  
                                </div>
                            </div>
                            <hr class="boder-b-0 my-4" />
                        @endforeach
                    </div>
                </div>
                {{-- END CONTENT --}}
            </div>
        </div>
    </div>

</x-app-layout>