routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductTypeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [OrderController::class, 'landing']);

Route::middleware(['auth:sanctum', 'verified'])->resource('product-types', ProductTypeController::class);
Route::middleware(['auth:sanctum', 'verified'])->resource('products', ProductController::class);
Route::middleware(['auth:sanctum', 'verified'])->resource('orders', OrderController::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $orders = DB::table('orders')
            ->join('clients', 'orders.client_id', '=', 'clients.id')
            ->get();

        return view('order.list', ['orders' => $orders]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }

    public function landing()
    {


        $products = DB::table('products')
            ->orderBy('created_at', 'desc')
            ->paginate(6);
        
        return view('order.landing', ['products' => $products]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/LandingLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class LandingLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.landing');
    }
}

resources/views/order/landing.blade.php
<x-landing-layout>
    <div id="page-wrapper">

        <!-- Header -->
        <section id="header">
            <div class="container">

                <!-- Logo -->
                <h1 id="logo"><a href="#">YUDA</a></h1>
                <p>Comercializadora.</p>

                <!-- Nav -->
                <nav id="nav">
                    {{-- <ul>
                        <li><a class="icon solid fa-home" href="index.html"><span>Introduction</span></a></li>
                        <li>
                            <a href="#" class="icon fa-chart-bar"><span>Dropdown</span></a>
                            <ul>
                                <li><a href="#">Lorem ipsum dolor</a></li>
                                <li><a href="#">Magna phasellus</a></li>
                                <li><a href="#">Etiam dolore nisl</a></li>
                                <li>
                                    <a href="#">Phasellus consequat</a>
                                    <ul>
                                        <li><a href="#">Magna phasellus</a></li>
                                        <li><a href="#">Etiam dolore nisl</a></li>
                                        <li><a href="#">Phasellus consequat</a></li>
                                    </ul>
                                </li>
                                <li><a href="#">Veroeros feugiat</a></li>
                            </ul>
                        </li>
                        <li><a class="icon solid fa-cog" href="left-sidebar.html"><span>Left Sidebar</span></a></li>
                        <li><a class="icon solid fa-retweet" href="right-sidebar.html"><span>Right
                                    Sidebar</span></a></li>
                        <li><a class="icon solid fa-sitemap" href="no-sidebar.html"><span>No Sidebar</span></a></li>
                    </ul> --}}
                </nav>

            </div>
        </section>

        <!-- Banner -->
        {{-- <section id="banner">
            <div class="container">
                <p>Comercial.<br />
                   e <strong>Industrial</strong>.</p>
            </div>
        </section> --}}


        <!-- Features -->
        <section id="features">
            <div class="container">
                <header>
                    <h2>Comercial e <strong>Industrial</strong>!</h2>
                </header>
                <div class="row aln-center">
                    @foreach ($products as $product)
                        <div class="col-4 col-6-medium col-12-small">

                            <!-- Feature -->
                            <section>
                                <a href="#" class="image featured">
                                    <img src="{{ URL::to('/') }}/storage/images/{{ $product->image }}" alt="" />
                                </a>
                                <header>
                                    <h3>{{ $product->name }}</h3>
                                </header>
                                <p>
                                    {{ $product->description }}
                                </p>
                            </section>

                        </div>
                    @endforeach
                    
                    <div class="col-12">
                        
                        <ul class="actions">
                            {{ $products->links('pagination::semantic-ui') }}
                            
                            {{-- <li><a href="#" class="button icon solid fa-file">Tell Me More</a></li> --}}
                        </ul>
                    </div>
                </div>
            </div>
        </section>

        <!-- Main -->
        

        <!-- Footer -->
        <section id="footer">
            <div class="container">
                <header>
                    <h2>Questions or comments? <strong>Get in touch:</strong></h2>
                </header>
                <div class="row">
                    <div class="col-6 col-12-medium">
                        <section>
                            <form method="post" action="#">
                                <div class="row gtr-50">
                                    <div class="col-6 col-12-small">
                                        <input name="name" placeholder="Name" type="text" />
                                    </div>
                                    <div class="col-6 col-12-small">
                                        <input name="email" placeholder="Email" type="text" />
                                    </div>
                                    <div class="col-12">
                                        <textarea name="message" placeholder="Message"></textarea>
                                    </div>
                                    <div class="col-12">
                                        <a href="#" class="form-button-submit button icon solid fa-envelope">Send
                                            Message</a>
                                    </div>
                                </div>
                            </form>
                        </section>
                    </div>
                    <div class="col-6 col-12-medium">
                        <section>
                            <p>Erat lorem ipsum veroeros consequat magna tempus lorem ipsum consequat Phaselamet
                                mollis tortor congue. Sed quis mauris sit amet magna accumsan tristique. Curabitur
                                leo nibh, rutrum eu malesuada.</p>
                            <div class="row">
                                <div class="col-6 col-12-small">
                                    <ul class="icons">
                                        <li class="icon solid fa-home">
                                            1234 Somewhere Road<br />
                                            Nashville, TN 00000<br />
                                            USA
                                        </li>
                                        <li class="icon solid fa-phone">
                                            (000) 000-0000
                                        </li>
                                        <li class="icon solid fa-envelope">
                                            <a href="#">info@untitled.tld</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-6 col-12-small">
                                    <ul class="icons">
                                        <li class="icon brands fa-twitter">
                                            <a href="#">@untitled</a>
                                        </li>
                                        <li class="icon brands fa-instagram">
                                            <a href="#">instagram.com/untitled</a>
                                        </li>
                                        <li class="icon brands fa-dribbble">
                                            <a href="#">dribbble.com/untitled</a>
                                        </li>
                                        <li class="icon brands fa-facebook-f">
                                            <a href="#">facebook.com/untitled</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
            <div id="copyright" class="container">
                <ul class="links">
                    <li>&copy; Untitled. All rights reserved.</li>
                    <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
                </ul>
            </div>
        </section>

    </div>



</x-landing-layout>

resources/views/order/list.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Ordenes') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                {{-- INIT CONTENT --}}
                <div class="flex justify-center py-2 px-2">

                    <div class=" w-3/4 rounded px-6"> {{-- bg-gray-100 --}}
                        <div class="border-l-4 border-indigo-400 -ml-6 pl-6 flex items-center justify-between my-4">
                            {{-- <div class="font-semibold text-gray-800">
                                Ordenes
                            </div> --}}
                            <div class="text-indigo-400">See all</div>
                        </div>
                        {{-- <hr class="-mx-6" /> --}}
                      


                        <table class="table-auto">
                            <thead>
                                <tr>
                                    <th class="w-1/2 px-4 py-2">Cliente</th>
                                    <th class="w-1/4 px-4 py-2">Folio</th>
                                    <th class="w-1/4 px-4 py-2">Telefono</th>
                                    <th class="w-1/4 px-4 py-2">Tipo</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($orders as $order)
                                    <tr>
                                        <td class="border px-4 py-2">{{ $order->name }}</td>
                                        <td class="border px-4 py-2">{{ $order->folio }}</td>
                                        <td class="border px-4 py-2">{{ $order->phone }}</td>
                                        <td class="border px-4 py-2">
                                            @if ($order->is_wholesale)
                                                <span
                                                    class="flex rounded-full bg-indigo-500 text-white uppercase px-2 py-1 text-xs font-bold mr-3">
                                                    {{ 'Mayoreo' }}
                                                </span>
                                            @else
                                                <span
                                                    class="flex rounded-full bg-pink-500 text-white uppercase px-2 py-1 text-xs font-bold mr-3">
                                                    {{ 'Menudeo' }}
                                                </span>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <br>
                    </div>
                </div>

                {{-- <form id="deleteForm"
                    action="{{ route('orders.destroy', $order->id) }}" method="POST">
                    <x-jet-nav-link href="{{ route('orders.edit', $order->id) }}"
                        :active="request()->routeIs('orders')">
                        <i class="fa fa-edit fa-lg text-indigo-400 mr-4"></i>
                    </x-jet-nav-link>

                    @csrf
                    @method('DELETE')

                    <button type="submit" title="delete" style="border: none; background-color:transparent;"
                        onclick="return confirm('¿Esta seguro que desea eliminar?')">
                        <i class="text-indigo-400 fas fa-trash fa-lg text-danger"></i>

                    </button>
                </form> --}}

                {{-- END CONTENT --}}
            </div>
        </div>
    </div>

</x-app-layout>